#source libs/gmp.bash
#source libs/guile.bash
source libs/blas.bash
source libs/lapack.bash
source libs/atlas.bash
source libs/gsl.bash
source libs/zlib.bash
source libs/openmpi.bash
#source libs/git.bash
source libs/scalapack.bash
source libs/hdf5.bash
source libs/hdf5-serial.bash
source libs/parallel-netcdf.bash
source libs/netcdf.bash
source libs/fftw2.bash
source libs/fftw2-serial.bash
source libs/fftw3.bash
source libs/fftw3-serial.bash
