# Common options for each of the GCC-compliers
pack_set -module-opt "-prepend-ENV LD_LIBRARY_PATH=$(pack_get -prefix)/lib"
pack_set -module-opt "-prepend-ENV LD_LIBRARY_PATH=$(pack_get -prefix)/lib64"
pack_set -module-opt "-undefined-ENV CC=gcc"
pack_set -module-opt "-undefined-ENV CXX=g++"
pack_set -module-opt "-undefined-ENV FC=gfortran"
pack_set -module-opt "-undefined-ENV F77=gfortran"
pack_set -module-opt "-undefined-ENV F90=gfortran"
pack_set -module-opt "-undefined-ENV AR=gcc-ar"
pack_set -module-opt "-undefined-ENV RANLIB=gcc-ranlib"
pack_set -module-opt "-undefined-ENV NM=gcc-nm"
